"use client"

import { useEffect, useRef } from "react"
import {
  AdvancedMarker,
  APIProvider,
  Map,
  useMap,
} from "@vis.gl/react-google-maps"
import { rankColor } from "@/lib/gbp-heatmap"

// Inlined at build time. When unset, the parent page falls back to the
// SVG grid; this component never renders without a key.
const API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
// AdvancedMarker requires a mapId. Google provides "DEMO_MAP_ID" for
// development; for production, create a Map ID in Cloud Console → Maps
// → Map Management and override via NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID.
const MAP_ID = process.env.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID ?? "DEMO_MAP_ID"

export type HeatmapPoint = {
  row: number
  col: number
  lat: number
  lng: number
}

export type HeatmapGridDef = {
  rows: number
  cols: number
  spacing_km: number
  points: HeatmapPoint[]
}

export function isGoogleMapsConfigured(): boolean {
  return Boolean(API_KEY)
}

/**
 * Heatmap map.
 *
 * `grid.points` defines the fixed 5×7 lattice of vantage points around the
 * scanned business — these never change between target ↔ competitor views.
 * `ranks` is a parallel array (same length, same index order) giving the
 * rank to render at each grid point for the currently-selected entity.
 * `markerLat/Lng/Title` describe the red pin overlay — the target's GBP by
 * default, the competitor's GBP when one is selected.
 */
export function HeatmapMap({
  grid,
  ranks,
  markerLat,
  markerLng,
  markerTitle,
}: {
  grid: HeatmapGridDef
  ranks: (number | null)[]
  markerLat: number
  markerLng: number
  markerTitle: string
}) {
  if (!API_KEY) return null

  return (
    <APIProvider apiKey={API_KEY}>
      <div className="h-[660px] w-full overflow-hidden rounded-lg border border-line">
        <Map
          mapId={MAP_ID}
          defaultCenter={{ lat: markerLat, lng: markerLng }}
          defaultZoom={12}
          gestureHandling="cooperative"
          mapTypeControl={false}
          streetViewControl={false}
          fullscreenControl={false}
        >
          {/* Fit-bounds runs once, against the immutable grid lattice, so
              flipping between competitors doesn't reframe the map. */}
          <FitGridOnce points={grid.points} />
          <AdvancedMarker
            position={{ lat: markerLat, lng: markerLng }}
            title={markerTitle}
            zIndex={1000}
          >
            <BusinessMarker />
          </AdvancedMarker>
          {grid.points.map((p, i) => (
            <AdvancedMarker
              key={`${p.row}-${p.col}`}
              position={{ lat: p.lat, lng: p.lng }}
              title={`Row ${p.row + 1}, Col ${p.col + 1} · rank ${
                ranks[i] ?? "out of top 100"
              }`}
            >
              <RankCircle rank={ranks[i] ?? null} />
            </AdvancedMarker>
          ))}
        </Map>
      </div>
    </APIProvider>
  )
}

export type DrawnCircle = {
  lat: number
  lng: number
  radiusMeters: number
}

/**
 * Map with a single editable + draggable circle the user "draws" to define a
 * custom scan area. The circle is the source of truth during interaction: drag
 * to recenter, drag the edge handles to resize, and both fire `onCircleChange`.
 * `previewPoints` are the vantage points that currently fall inside the circle
 * (generated by the parent) and render as small dots so the user sees exactly
 * what will be scanned.
 */
export function CircleDrawMap({
  center,
  circle,
  onCircleChange,
  previewPoints,
}: {
  center: { lat: number; lng: number }
  circle: DrawnCircle
  onCircleChange: (next: DrawnCircle) => void
  previewPoints: { lat: number; lng: number }[]
}) {
  if (!API_KEY) return null
  return (
    <APIProvider apiKey={API_KEY}>
      <div className="h-[660px] w-full overflow-hidden rounded-lg border border-line">
        <Map
          mapId={MAP_ID}
          defaultCenter={{ lat: center.lat, lng: center.lng }}
          defaultZoom={11}
          gestureHandling="cooperative"
          mapTypeControl={false}
          streetViewControl={false}
          fullscreenControl={false}
        >
          <EditableCircle circle={circle} onChange={onCircleChange} />
          <AdvancedMarker
            position={{ lat: center.lat, lng: center.lng }}
            title="Business location"
            zIndex={1000}
          >
            <BusinessMarker />
          </AdvancedMarker>
          {previewPoints.map((p, i) => (
            <AdvancedMarker key={i} position={{ lat: p.lat, lng: p.lng }}>
              <PreviewDot />
            </AdvancedMarker>
          ))}
        </Map>
      </div>
    </APIProvider>
  )
}

function EditableCircle({
  circle,
  onChange,
}: {
  circle: DrawnCircle
  onChange: (next: DrawnCircle) => void
}) {
  const map = useMap()
  const ref = useRef<google.maps.Circle | null>(null)
  const onChangeRef = useRef(onChange)
  useEffect(() => {
    onChangeRef.current = onChange
  }, [onChange])

  // Create the circle once when the map is ready. Initial geometry comes from
  // the first `circle` prop; subsequent external changes are synced below.
  useEffect(() => {
    if (!map) return
    const c = new google.maps.Circle({
      map,
      center: { lat: circle.lat, lng: circle.lng },
      radius: circle.radiusMeters,
      editable: true,
      draggable: true,
      strokeColor: "#1d4ed8",
      strokeOpacity: 0.9,
      strokeWeight: 2,
      fillColor: "#3b82f6",
      fillOpacity: 0.08,
    })
    ref.current = c
    const emit = () => {
      const ctr = c.getCenter()
      if (ctr) {
        onChangeRef.current({
          lat: ctr.lat(),
          lng: ctr.lng(),
          radiusMeters: c.getRadius(),
        })
      }
    }
    const listeners = [
      c.addListener("radius_changed", emit),
      c.addListener("center_changed", emit),
      c.addListener("dragend", emit),
    ]
    return () => {
      listeners.forEach((l) => l.remove())
      c.setMap(null)
      ref.current = null
    }
    // Create once; external updates handled by the sync effect below.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map])

  // Sync external prop changes (e.g. the radius slider) onto the live circle.
  // Guarded so we don't re-set a value the circle already has, which would
  // bounce back through `emit` in a loop.
  useEffect(() => {
    const c = ref.current
    if (!c) return
    if (Math.abs(c.getRadius() - circle.radiusMeters) > 0.5) {
      c.setRadius(circle.radiusMeters)
    }
    const ctr = c.getCenter()
    if (ctr && (ctr.lat() !== circle.lat || ctr.lng() !== circle.lng)) {
      c.setCenter({ lat: circle.lat, lng: circle.lng })
    }
  }, [circle.lat, circle.lng, circle.radiusMeters])

  return null
}

function PreviewDot() {
  return (
    <div
      style={{
        width: 10,
        height: 10,
        borderRadius: 5,
        background: "#1d4ed8",
        border: "1.5px solid white",
        boxShadow: "0 1px 2px rgba(0,0,0,0.35)",
        transform: "translateY(5px)",
      }}
    />
  )
}

function RankCircle({ rank }: { rank: number | null }) {
  return (
    <div
      style={{
        width: 36,
        height: 36,
        borderRadius: 18,
        background: rankColor(rank),
        color: "white",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "system-ui, sans-serif",
        fontSize: 13,
        fontWeight: 600,
        border: "2px solid white",
        boxShadow: "0 1px 3px rgba(0, 0, 0, 0.35)",
        userSelect: "none",
        transform: "translateY(18px)",
      }}
    >
      {rank == null ? "—" : rank}
    </div>
  )
}

function BusinessMarker() {
  return (
    <div
      style={{
        width: 22,
        height: 22,
        borderRadius: 11,
        background: "#FF1E00",
        border: "3px solid white",
        boxShadow: "0 1px 4px rgba(0, 0, 0, 0.45)",
        transform: "translateY(11px)",
      }}
      aria-label="Business location"
    />
  )
}

/**
 * Fit the map viewport to the grid lattice exactly once, on first paint.
 * Subsequent re-renders (e.g. when the user picks a different competitor)
 * keep the same bounds so the user's mental model of the map doesn't shift.
 */
function FitGridOnce({ points }: { points: HeatmapPoint[] }) {
  const map = useMap()
  const fittedRef = useRef(false)
  useEffect(() => {
    if (!map || fittedRef.current || points.length === 0) return
    const bounds = new google.maps.LatLngBounds()
    for (const p of points) bounds.extend({ lat: p.lat, lng: p.lng })
    map.fitBounds(bounds, 40)
    fittedRef.current = true
  }, [map, points])
  return null
}
